CREATE TABLE [LOTR].[EventCard]
(
[EventID] [int] NOT NULL IDENTITY(1, 1),
[CardId] [int] NULL,
[Cost] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [LOTR].[EventCard] ADD CONSTRAINT [PK__EventCar__7944C8707DE34A64] PRIMARY KEY CLUSTERED ([EventID]) ON [PRIMARY]
GO
ALTER TABLE [LOTR].[EventCard] ADD CONSTRAINT [FK__EventCard__CardI__71D1E811] FOREIGN KEY ([CardId]) REFERENCES [LOTR].[Card] ([CardID])
GO
