CREATE TABLE [LOTR].[DeckCards]
(
[DeckCardID] [int] NOT NULL IDENTITY(1, 1),
[DeckID] [int] NULL,
[CardID] [int] NULL,
[quantity] [int] NULL,
[RowVer] [timestamp] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [LOTR].[DeckCards] ADD CONSTRAINT [PK__DeckCard__EFEAFFC11E5A3512] PRIMARY KEY CLUSTERED ([DeckCardID]) ON [PRIMARY]
GO
ALTER TABLE [LOTR].[DeckCards] ADD CONSTRAINT [FK__DeckCards__CardI__208CD6FA] FOREIGN KEY ([CardID]) REFERENCES [LOTR].[Card] ([CardID])
GO
ALTER TABLE [LOTR].[DeckCards] ADD CONSTRAINT [FK__DeckCards__DeckI__2180FB33] FOREIGN KEY ([DeckID]) REFERENCES [LOTR].[Deck] ([DeckID])
GO
