CREATE TABLE [LOTR].[DeckHeroes]
(
[DeckHeroesID] [int] NOT NULL IDENTITY(1, 1),
[DeckID] [int] NULL,
[CardID] [int] NULL,
[RowVer] [timestamp] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [LOTR].[DeckHeroes] ADD CONSTRAINT [PK__DeckHero__0BA53765E82D531A] PRIMARY KEY CLUSTERED ([DeckHeroesID]) ON [PRIMARY]
GO
ALTER TABLE [LOTR].[DeckHeroes] ADD CONSTRAINT [FK__DeckHeroe__CardI__1332DBDC] FOREIGN KEY ([CardID]) REFERENCES [LOTR].[Card] ([CardID])
GO
ALTER TABLE [LOTR].[DeckHeroes] ADD CONSTRAINT [FK__DeckHeroe__DeckI__123EB7A3] FOREIGN KEY ([DeckID]) REFERENCES [LOTR].[Deck] ([DeckID])
GO
