CREATE TABLE [LOTR].[DeckCards]
(
[DeckCardID] [int] NOT NULL IDENTITY(1, 1),
[DeckID] [int] NULL,
[CardID] [int] NULL,
[RowVer] [timestamp] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [LOTR].[DeckCards] ADD CONSTRAINT [PK__DeckCard__EFEAFFC13A62C453] PRIMARY KEY CLUSTERED ([DeckCardID]) ON [PRIMARY]
GO
ALTER TABLE [LOTR].[DeckCards] ADD CONSTRAINT [FK__DeckCards__CardI__0A9D95DB] FOREIGN KEY ([CardID]) REFERENCES [LOTR].[Card] ([CardID])
GO
ALTER TABLE [LOTR].[DeckCards] ADD CONSTRAINT [FK__DeckCards__DeckI__09A971A2] FOREIGN KEY ([DeckID]) REFERENCES [LOTR].[Deck] ([DeckID])
GO
